const Map<String, String> collegeCode = {
  "Adaikalamatha College": "login6455",
  "Adhiparasakthi College Of Arts And Science": "login4243",
  "Adhiparasakthi Engineering College": "login1169",
  "Adhiyamaan College of Engineering": "login2495",
  "Alagappa Chettiar College of Engineering and Technology": "login3635",
  "Ambal Professional Group of Institutions": "login7414",
  "Amity University - Lucknow": "login7307",
  "Amity University - Gwalior": "login8961",
  "Amity University - Haryana": "login1500",
  "Amrita College of Engineering and Technology": "login1573",
  "Amrita School of Arts & Sciences": "login5864",
  "Amrita University - Coimbatore": "login3686",
  "Amrita University - Mysure": "login8998",
  "Anjalai Ammal Mahalingam Engineering College": "login1316",
  "Anna University - Coimbatore": "login2225",
  "Anna University -Tiruchirappalli": "login5997",
  "Annai Mathammal Sheela Engineering College": "login8617",
  "Annapoorana Engineering College": "login4636",
  "Apollo Engineering College": "login2468",
  "Arasu Engineering College": "login1840",
  "ARJ College of Engineering and Technology": "login2706",
  "ARM College of Engineering and Technology": "login4067",
  "ARS College of Engineering ": "login6377",
  "Arulanandar College": "login3839",
  "Arulmigu Meenakshi Amman College of Engineering": "login1416",
  "Arunai Engineering College": "login9919",
  "Asan Memorial College Of Arts And Science": "login4062",
  "AVC College of Engineering": "login9017",
  "Avinashilingam University for Women": "login5732",
  "Birla Institute of Technology & Science": "login1545",
  "Bishop Heber College": "login3150",
  "BITS Pilani": "login3448",
  "C. Abdul Hakeem College of Engineering & Technology": "login5496",
  "C.S.I Institute Of Technology": "login3040",
  "Chennai Institute of Technology": "login8584",
  "Christ University science": "login1583",
  "Coimbatore Insititute Of Management And Technology": "login4264",
  "Coimbatore Institute of Technology": "login9602",
  "College Of Engineering: Guindy": "login7914",
  "CSI Bishop Appasamy College Of Arts And Science": "login9776",
  "Dr. Mahalingam College of Engineering & Technology": "login3995",
  "Dr. NGP Arts and Science College": "login2676",
  "Dr. NGP Institute Of Technology": "login9242",
  "Dr. SNS Rajalakshmi College Of Arts And Science": "login2980",
  "EGS Pillay Engineering College": "login6992",
  "Erode Arts & Science College": "login1667",
  "Government College For Men": "login9459",
  "Government Thirumagal Mills College": "login6946",
  "GRT Institute of Engineering and Technology": "login5632",
  "Hindusthan College Of Arts And Science": "login8863",
  "Hindusthan College of Engineering and Technology": "login6533",
  "Holy Cross College": "login2224",
  "IIT - Bombay": "login3990",
  "IIT - Delhi": "login3391",
  "IIT - Dharwad": "login7795",
  "IIT - Goa": "login2840",
  "IIT - Guwahati": "login7432",
  "IIT - Hyderabad": "login1313",
  "IIT - Indore": "login5347",
  "IIT - Jammu": "login6167",
  "IIT - Jharkhand": "login5423",
  "IIT - Jodhpur": "login1532",
  "IIT - Kanpur": "login3787",
  "IIT - Chennai": "login2274",
  "IIT - Palakkad": "login8597",
  "IIT - Patna": "login9085",
  "IIT - Rajpur": "login2227",
  "IIT - Roorkee": "login3680",
  "IIT - Ropar": "login1562",
  "IIT - Varanasi": "login6037",
  "Indira Institute of Engineering and Technology": "login1139",
  "Info Institute Of Engineering": "login8461",
  "Institute Of Road And Transport Technology": "login1168",
  "Jadavpur University": "login6852",
  "Jamal Mohamed College": "login4843",
  "Jaya Engineering College": "login3439",
  "Jayam College of Engineering and Technology ": "login5139",
  "Jayaram College of Engineering and Technology": "login1352",
  "JBAS College For Women": "login4322",
  "Jeppiaar Engineering College": "login5903",
  "Jerusalem College of Engineering": "login7502",
  "JKK Nadaraja Women Arts And Science": "login8267",
  "JNTUH Institute Of Science And Technology": "login9288",
  "Joy University": "login1919",
  "Kalaignar Karunanidhi Institute of Technology": "login3069",
  "Kalasalingam University": "login3406",
  "Kamaraj College": "login1914",
  "Karpaga Vinayaga College of Engineering And Technology": "login8022",
  "Karpagam Arts And Science College": "login8592",
  "Karpagam College of Engineering": "login7321",
  "Karunya University": "login8503",
  "Kathir college of Engineering": "login3291",
  "KCG College of Technology": "login8500",
  "KGISL Institute Of Information Management": "login9950",
  "KGISL Institute of Technology": "login3940",
  "Khadir Mohideen College": "login8474",
  "Kingston Engineering College": "login6808",
  "KLN College of Engineering": "login7540",
  "Kongu Arts And Science College": "login1279",
  "Kongu Engineering College": "login5268",
  "Krishnasamy College of Engineering and Technology": "login5533",
  "KRS College of Engineering": "login5673",
  "KSR College of Engineering": "login6810",
  "Kumaraguru College of Technology": "login7847",
  "Kurinji College Of Arts And Science": "login1994",
  "Lady Doak College": "login8012",
  "Lord Jegannath College of Engineering and Technology": "login5585",
  "Loyola College": "login1103",
  "Loyola Institute Of Technology": "login7372",
  "M. Kumarasamy College of Engineering": "login1793",
  "Madha Engineering College": "login4479",
  "Madras Christian College": "login4950",
  "Madras Institute of Technology": "login1403",
  "Mahendra Engineering College": "login8231",
  "Mailam Engineering College": "login5551",
  "MAM College of Engineering": "login9642",
  "Marudhar Kesari Jain College For Women": "login1536",
  "Measi Institute Of Information Technology": "login1794",
  "Meenakshi College For Women": "login6779",
  "Meenakshi College of Engineering ": "login9693",
  "Meenakshi Ramaswamy Engineering College": "login3582",
  "Mepco Schlenk Engineering College": "login6812",
  "Mohamed Sathak College Of Arts And Science": "login7804",
  "Mohamed Sathak Engineering College": "login7687",
  "MP Nachimuthu M Jaganathan Engineering College": "login7705",
  "Muthayammal Engineering College ": "login2814",
  "Nadar Saraswathi College Of Arts & Science": "login6034",
  "Nandha Engineering College": "login1772",
  "National Engineering College": "login7636",
  "Nehru College Of Management": "login5928",
  "Nehru Institute of Engineering and Technology": "login1135",
  "Nehru Institute of Information Technology and Management": "login7855",
  "Nesamony Memorial Christian College": "login7046",
  "New Prince Shri Bhavani College of Engineering And Technology": "login6408",
  "NIT - Allahabad": "login8586",
  "NIT - Andhra Pradesh": "login8432",
  "NIT - Bhopal": "login7030",
  "NIT - Calicut": "login4716",
  "NIT - Delhi": "login7547",
  "NIT - Durgapur": "login3676",
  "NIT - Goa": "login4290",
  "NIT - Hamirpur": "login5710",
  "NIT - Jaipur": "login9745",
  "NIT - Jalandhar": "login7168",
  "NIT - Jamshedpur": "login1498",
  "NIT - Karnataka": "login8995",
  "NIT - Manipur": "login2536",
  "NIT - Meghalaya": "login3237",
  "NIT - Mizoram": "login2042",
  "NIT - Nagpur": "login3514",
  "NIT - Patna": "login1023",
  "NIT - Pudhucherry": "login3524",
  "NIT - Raipur": "login4302",
  "NIT - Rourkela": "login8928",
  "NIT - Sikkim": "login8764",
  "NIT - Silchar": "login2986",
  "NIT - Surat": "login6370",
  "NIT - Trichy": "login6159",
  "NIT - Uttarakhand": "login9454",
  "NIT -Warangal": "login7757",
  "NIT - Haryana": "login6722",
  "NIT - Tripura": "login3810",
  "NIT - Papum Pare": "login3835",
  "Oxford College of Engineering": "login9795",
  "Paavai Engineering College": "login1669",
  "Pallavan College of Engineering": "login4059",
  "Park College Of Engineering And Technology": "login7478",
  "Pavendar Bharathidasan College Of Engineering And Technology": "login4825",
  "PEE GEE College Of Arts & Science": "login5326",
  "PET Engineering College ": "login7316",
  "PGP College Of Arts And Science": "login5783",
  "PGP College of Engineering and Technology": "login8160",
  "PKR Arts College For Women": "login4287",
  "Pondicherry University": "login8509",
  "PR Engineering College": "login4536",
  "Presidency College": "login9189",
  "Prince Shri Venkateshwara Padmavathy Engineering College": "login3968",
  "Priyadarshini Engineering College": "login5622",
  "Professional Group Of Institutions": "login1911",
  "PSG College Of Arts And Science": "login4709",
  "PSGR Krishnammal College for Women": "login8433",
  "PSN College of Engineering And Technology ": "login4982",
  "PSNA College of Engineering and Technology": "login3796",
  "Quaid-E-Milliath Government College For Women": "login7343",
  "Queen Mary's College": "login2749",
  "R V College of Engineering": "login4899",
  "Rajalakshmi Engineering College": "login1225",
  "Rajiv Gandhi College of Engineering": "login8813",
  "Rathinam College of Arts and Science": "login1648",
  "RMK Engineering College": "login1145",
  "Roever Engineering College ": "login9515",
  "RVS College Of Arts And Science": "login9078",
  "RVS College of Computer Application": "login7209",
  "RVS College of Engineering": "login6354",
  "SA Engineering College": "login6048",
  "S Veerasamy Chettiar College of Engineering and Technology": "login1800",
  "SRM Arts And Science College": "login6898",
  "Sacred Heart College": "login9877",
  "Salem Sowdeswari College": "login3881",
  "San International Info School": "login8648",
  "Sankara College Of Science And Commerce": "login1079",
  "Sarah Tucker College For Women": "login9030",
  "Sardar Raja College of Engineering": "login7530",
  "Sastra University": "login2023",
  "Sasurie College Of Engineering": "login6772",
  "Sathyabama University": "login7182",
  "Scott Christian College": "login2685",
  "Selvam College of Technology": "login1746",
  "Sengunthar Arts and Science College": "login7446",
  "Sengunthar College Of Engineering": "login9770",
  "Shanmuga Industries Arts & Science College": "login9358",
  "Shreenivasa Engineering College": "login7064",
  "SIGA College of Management and Computer Science": "login7700",
  "Sivanthi Aditanar College": "login2074",
  "SKSS Arts College": "login2350",
  "SNS College of Engineering": "login6497",
  "SNS College of Technology": "login2361",
  "Sona College of Technology": "login9160",
  "Sourashtra College": "login6622",
  "Sree Amman Arts & Science College": "login5537",
  "Sree Saraswathi Thyagaraja College": "login6751",
  "SRG Engineering College": "login2409",
  "Sri Balaji Chockalingam Engineering College": "login5620",
  "Sri Chandrasekharendra Saraswathi Viswa Maha Vidyalaya": "login6986",
  "Sri Krishna Arts and Science College": "login1834",
  "Sri Krishna College of Engineering and Technology": "login5824",
  "Sri Meenakshi Government Arts college for women ": "login5631",
  "Sri Muthukumaran Institute of Technology": "login2424",
  "Sri Ramakrishna College Of Arts & Science For Women": "login5671",
  "Sri Ramakrishna College of Arts and Science": "login5769",
  "Sri Ramakrishna Engineering College": "login5230",
  "Sri Ramakrishna Mission Vidyalaya College Of Arts & Science": "login4915",
  "Sri SaiRam Engineering College": "login9303",
  "Sri Sairam Institute of Technology": "login4262",
  "Sri Sankara Arts and Science College-MSC": "login1029",
  "Sri Sarada College For Women": "login3446",
  "Sri Sarada Niketan College Of Science For Women": "login9815",
  "Sri Shanmugha College of Engineering and Technology": "login5018",
  "Sri Subramaniaswamy Government Arts College": "login6424",
  "Sri Venkateswara College of Engineering": "login1868",
  "SRM - Delhi": "login1894",
  "ST Hindu College": "login7283",
  "St. Joseph College of Engineering Chennai": "login7340",
  "St. Joseph College of Engineering Kanchipuram": "login9509",
  "St. Joseph College of Engineering Bengaluru": "login6575",
  "St. Xaviers Catholic College of Engineering": "login3088",
  "Stella Maris College": "login3288",
  "STET School Of Management": "login3243",
  "Tagore Engineering College": "login2188",
  "Tamilnadu College Of Engineering": "login7715",
  "Tamilavel Uma Maheswaranar Karanthai Arts College": "login1776",
  "Thangavelu Engineering College": "login1612",
  "Thanthai Periyar Government Institute Of Technology": "login9584",
  "Thassim Beevi Abdul Kader College For Women": "login2507",
  "The American College": "login8511",
  "The Ethiraj College For Women": "login1473",
  "The Kavery Engineering College": "login6045",
  "The New College": "login8448",
  "The Rajas Engineering College": "login8353",
  "The Standard Fireworks Rajaratnam College For Women": "login3463",
  "Theivani Ammal College For Women": "login1935",
  "Thiagarajar College of Engineering": "login3486",
  "Thirumalai Engineering College": "login9332",
  "Thiruvalluvar College of Engineering and Technology": "login7246",
  "Tranquebar Bishop Manikam Lutheran College": "login5799",
  "Trichy Engineering College": "login9207",
  "Udaya School of Engineering": "login8629",
  "United Institute Of Technology": "login7315",
  "University of Delhi": "login9937",
  "University of Hyderabad": "login2838",
  "University of Kerala": "login1078",
  "University of Lucknow": "login4952",
  "University of Madras": "login8460",
  "University Of Mysore": "login3891",
  "V.V. Vanniaperumal College For Women": "login2268",
  "Valliammal College for Women": "login3300",
  "Varuvan Vadivelan Institute of Technology": "login7086",
  "Vel Tech High Tech Dr. Rangarajan Dr.  Sakunthala Engineering College ": "login8664",
  "Velalar College of Engineering and Technology": "login8644",
  "Velammal Engineering College": "login4286",
  "Vellalar College For Women": "login5050",
  "VHN Senthikumara Nadar College": "login7413",
  "Vidyaa Vikas College of Engineering and Technology": "login4397",
  "Virudhunagar Hindu Nadar's Senthikumara Nadar College": "login5303",
  "VIT - Amaravathi": "login3625",
  "VIT -Chennai": "login4546",
  "VIT - Vellore": "login9628",
  "Vivekanandha College Of Arts And Science For Women": "login2133",
  "VSB Engineering College": "login3225",
  "Womens Christian College": "login5484",
  "Prathyusha Engineering College": "login4029",
  "Velammal College of Engineering and Technology": "login8185",
  "Kamaraja College Of Engineering & Technology": "login5655",
  "Solamalai College of Engineering": "login9629",
  "Fatima Michael College of Engineering and Technology": "login3432",
  "Latha Mathavan Group of Institution": "login7878",
  "Syed Ammal Engineering college": "login3898",
  "Tagore Institute of Engineering and Technology": "login4840",
  "Global institute of technology": "login7244",
  "Saveetha engineering college": "login7546",
  "Ranipettai Engineering College: Vellore": "login3516",
  "Priyadarshini Engineering College - Tirupattur": "login3566",
  "Bharathidasan Engineering College": "login9185",
  "ULTRA College of Engineering & Technology": "login9588",
  "Sri Sai Ram Institute of Technology": "login8938",
  "MRK Institute of technology": "login7313",
  "Arulmigu Meenakshi Amman College of Engineering Kanchipuram": "login5471",
  "EGS Pillay Engineering College Nagapattinam": "login4232",
  "Sembodai Rukmani Varatharajan Engineering College": "login8182",
  "Sir Issac Newton College of Engineering And Technology": "login1660",
  "JKKN Educational Institutions": "login2835",
  "Government College of Engineering": "login4374",
  "Arunachala College of Engineering for Women": "login1460",
  "Sri Sivasubramaniya Nadar College of Engineering": "login3806",
  "Joy University Tirunelveli": "login5333",
  "Ajeenkya DY Patil University": "login7203",
  "MIT World Peace University": "login9275",
  "GD Goenka University": "login9793",
  "Bharath Institute of Higher Education and Research": "login2142",
  "AC College of Engineering & Technology": "login7950",
  "Periyar Maniammai Institute of Science & Technology": "login3521",
  "Pachaiyappa's College": "login3431",
  "RMD Engineering College": "login4848",
  "Vinayaka Mission's Kirupananda Variyar Engineering College": "login8218",
  "SSM College of Engineering": "login3699"
};
const Map<String, String> degrees = {
  "ME": "ME",
  "MCA": "MCA",
  "M.Sc.": "MSC",
  "M.Tech.": "MTECH",
  "M.Com": "MCOM",
  "MA": "MA",
};
const streams = {
  "Computer Applications": "COMPUTER_APPLICATIONS",
  "Computer Science": "COMPUTER_SCIENCE",
  "Mathematics": "MATHEMATICS",
  "Other": "OTHER"
};
const Map<String, String> yearsOfStudy = {
  "1st Year": "1",
  "2nd Year": "2",
  "3rd Year": "3",
  "4th Year": "4",
  "5th Year": "5",
};
const Map<String, String> genders = {"Male": "M", "Female": "F"};

const Map<String, bool> accommodation = {"Yes": true, "No": false};

const Map<String, String> foodPreference = {"Veg": "VEG", "Non-Veg": "NON_VEG"};
